import {
  categoryFilter,
  audienceFilter,
  discountFilter,
} from './filter-options';

export default {
  settings: {
    dimensions: {
      width: 2600,
      height: 856,
    },
    boundaryShape: `M2599,196H1566V1H1V592H511v61h94v22H725V653h94V592h188v31.21A125,125,0,0,0,1072,855c35.22,0,121.5-37.5,121.5-37.5l752.28-.27a250.14,250.14,0,0,0,254.6-.09L2599,817Z`,
    innerBoundaryShape: `M1242,284V564h-96V284Zm831,406.5a39,39,0,1,0,39,39A39,39,0,0,0,2073,690.5Zm.11-259.89a52.39,52.39,0,1,0,52.4,52.39A52.38,52.38,0,0,0,2073.11,430.61ZM2149,716.75v20h94.5v-20Zm104.5,0v20H2348v-20Zm0-242.75v20H2348V474ZM1807.44,716.75v20h91.34v-20Zm101.34,0v20h91.34v-20Z`,
  },
  areas: [
    {
      id: 21,
      title: `Мама Чолли`,
      logoSrc: `mama-cholli.svg`,
      synonyms: ['чоли', 'vfvf xjkkb', 'vfvvf xjkkb'],
      description: `Итальянская пиццерия и кухня`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/92`,
      path: `M2543,750.5h56v33h-56Z`,
    },
    {
      id: 22,
      title: `Макдоналдс`,
      logoSrc: `mcdonalds.svg`,
      synonyms: ['mcdonalds', 'макдональдс', 'макдоналдс'],
      description: `Ресторан быстрого питания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/86`,
      path: `M2599,667.5h-56V561h56Z`,
    },
    {
      id: 23,
      title: `Asia Market`,
      logoSrc: `asia.svg`,
      synonyms: [
        'азия маркет',
        'азиа маркет',
        'асия',
        'азиямаркет',
        'fpbzvfhrtn',
        'fpbz vfhrtn',
      ],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/69`,
      path: `M2543,783.5h56V817h-56Z`,
    },
    {
      id: 24,
      title: `Хуторок`,
      logoSrc: `hutorok.svg`,
      synonyms: ['хуторок', '[enjhjr'],
      description: `Русская и украинская кухня`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/2`,
      path: `M2599,703.5v47h-56v-47Z`,
    },
    {
      id: 25,
      title: `Восточный дворик`,
      logoSrc: `vostochnyj-dvorik.svg`,
      synonyms: [
        'восточный дворик',
        'восточная еда',
        'восточная кухня',
        'djcnjzysq ldjhbr',
      ],
      description: `Восточная кухня`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/77`,
      path: `M2599,703.5h-56v-36h56Z`,
    },
    {
      id: 26,
      title: `Burger King`,
      logoSrc: `burgerking.svg`,
      synonyms: ['бургенкинг', 'burgerking', 'burger king'],
      description: `Фирменные бургеры и фастфуд`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/74`,
      path: `M2439,561v60h-44V561Z`,
    },
    {
      id: 27,
      title: `Subway`,
      logoSrc: `subway.svg`,
      synonyms: ['subway', 'субвей', 'сабвей'],
      description: `Сэндвичи и салаты`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/68`,
      path: `M2469,561v60h-30V561Z`,
    },
    {
      id: 28,
      title: `Крошка-Картошка`,
      logoSrc: `kartoshka.svg`,
      synonyms: ['крошка-картошка'],
      description: `Российская сеть кафе быстрого питания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/73`,
      path: `M2543,561v60h-36V561Z`,
    },
    {
      id: 29,
      title: `Дон Пиццерон`,
      logoSrc: `don.svg`,
      synonyms: ['пицца', 'дон пиццерон', 'пица', 'дон пицерон'],
      description: `Ресторан быстрого питания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/78`,
      path: `M2507,561v60h-38V561Z`,
    },
    {
      id: 210,
      title: `Silver Spoon`,
      logoSrc: `silverspoon.svg`,
      synonyms: [
        'сильвер спун',
        'споон',
        'silver spoon',
        'детская одежда',
        'школьная одежда',
        'школьная форма',
      ],
      description: `Детская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/110`,
      path: `M1949.93,784.82V751.14h50.19v33.68Z`,
    },
    {
      id: 211,
      title: `Eмае`,
      logoSrc: `emae.svg`,
      synonyms: [
        'ёмаё',
        'емае',
        'детская одежда',
        'дизайнерская одежда для детей',
        'одежда для детей',
      ],
      description: `Детская одежда для мальчиков и девочек`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/47`,
      path: `M1898.64,784.82V751.14h51.29v33.68Z`,
    },
    {
      id: 212,
      title: `ЗВУК МАСТЕР`,
      logoSrc: `zvuk-master.svg`,
      synonyms: [
        'звук мастер',
        'звукмастер',
        'мастер звука',
        'микрофоны',
        'наушники',
        'батарейки',
        'аккумуляторы',
        'фонари',
        'карты памяти',
        'компьютерные принадлежности',
        'кабельная продукция',
        'зарядные устройства',
        'автомагнитолы',
        'видеорегистраторы',
        'радар-детекторы',
        'усилители',
        'аккустические системы',
        'охранные сигнализации',
        'парковочные системы',
      ],
      description: `Аудио - видео продукция`,
      discount: new Set(),
      category: new Set([categoryFilter[`Бытовая техника, электроника`]]),
      audience: new Set(),
      shopURL: `/shop/159`,
      path: `M2149,784.82h-34.32L2149,750.5Z`,
    },
    {
      id: 213,
      title: `Antilopa`,
      logoSrc: `antilopa.svg`,
      synonyms: ['antilopa', 'антилопа', 'детская обувь', 'обувь для детей'],
      description: `Детская обувь`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/8`,
      path: `M1849.13,784.82V751.14h49.51v33.68Z`,
    },
    {
      id: 214,
      title: `АксТел`,
      logoSrc: `akstel.svg`,
      synonyms: [
        'акстел',
        'акс тел',
        'ремонт техники',
        'аксессуары для телефонов',
        'брелок',
        'брелоки брелки',
        'чехлы',
        'защитные пленки',
      ],
      description: `Ремонт техники, аксессуары для техники`,
      discount: new Set(),
      category: new Set([categoryFilter[`Бытовая техника, электроника`]]),
      audience: new Set(),
      shopURL: `/shop/142`,
      path: `M2000.12,784.82V751.14l33.68,33.68Z`,
    },
    {
      id: 215,
      title: `IDIZA`,
      logoSrc: `kriza.svg`,
      synonyms: ['криза', 'кризо', 'idiza', 'идиза'],
      description: `Изящные женские платья`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/57`,
      path: `M2149,784.82V750.5h51.38v34.32Z`,
    },
    {
      id: 216,
      title: `di Marko`,
      logoSrc: `dimarko.svg`,
      synonyms: ['ди марко', 'димарко', 'димакро', 'di marko'],
      description: `Итальянский ресторан`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/84`,
      path: `M2200.38,784.82v32.32a250.14,250.14,0,0,1-254.6.09l-145.92,0V784.82Z`,
    },
    // {
    //   id: 217,
    //   title: `Lo`,
    //   logoSrc: `lo.svg`,
    //   synonyms: [
    //     'ло',
    //     'одежда',
    //     'блузки',
    //     'платья',
    //     'lo',
    //     'янанедзвецкая',
    //     'jananedzvetskaya',
    //     'shopmisslocom',
    //     'russiandesigner',
    //     'купитьодежду',
    //     'женскаяодежда',
    //     'fashion',
    //     'dress',
    //     'купитьженскуюодежду',
    //     'платье',
    //     'clothing',
    //     'женская одежда',
    //   ],
    //   description: `Для женщин`,
    //   discount: new Set(),
    //   category: new Set([categoryFilter[`Одежда и аксессуары`]]),
    //   audience: new Set([audienceFilter[`Для женщин`]]),
    //   shopURL: `/shop/72`,
    //   path: `M2200.38,784.82V750.5h40.2v41.75h-40.2Z`,
    // },
    {
      id: 218,
      title: `1000 и 1 сумка`,
      logoSrc: `1000i1sumka.svg`,
      synonyms: [
        'сумки',
        '1001 сумка',
        'тысяча сумок',
        '1000 b 1 cevrf',
        'сумки',
        'портфели',
        'барсетки',
        'кейсы',
        'папки',
        'кожгалантерея',
      ],
      description: `Сумки и аксессуары`,
      discount: new Set(),
      category: new Set([categoryFilter[`Обувь, сумки, кожгалантерея`]]),
      audience: new Set(),
      shopURL: `/shop/1`,
      path: `M2284.54,750.5v66.61l-44,0h-40.2V792.25h40.2V750.5Z`,
    },
    {
      id: 219,
      title: `KFC`,
      logoSrc: `kfc.svg`,
      synonyms: ['кфс', 'kfc', 'киэфси', 'чикен', 'нагетсы'],
      description: `Ресторан быстрого питания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/79`,
      path: `M2363.36,750.5v66.58l-78.82,0V750.5Z`,
    },
    {
      id: 220,
      title: `Империя декора`,
      logoSrc: `imperiya-dekora.svg`,
      synonyms: ['империя декора'],
      description: `Декоративные материалы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/47`,
      path: `M1193.5,756.44V670.67h32.64v85.77Z`,
    },
    {
      id: 221,
      title: `Askona`,
      logoSrc: `askona.svg`,
      synonyms: ['аскона', 'оскона', 'fcrjyf'],
      description: `Товары для сна`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/35`,
      path: `M1300,670.67V817.46l-106.5,0V756.44h32.64V670.67Z`,
    },
    {
      id: 222,
      title: `PVS MEBEL`,
      logoSrc: `pvs-mebel.svg`,
      synonyms: ['pvs mebel'],
      description: `Фабрика мебели`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/42`,
      path: `M1147.17,704l33.49-33.33h12.84v85.77h-46.33Z`,
    },
    {
      id: 223,
      title: `Котофей`,
      logoSrc: `kotofey.svg`,
      synonyms: [
        'котофей',
        'кот',
        'обувь для детей',
        'обувь для подростков',
        'детская обувь',
        'удобная обувь',
      ],
      description: `Обувь для подростков и детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/166`,
      path: `M1682.89,751.14v66.19l-64.16,0V751.14Z`,
    },
    {
      id: 224,
      title: `Орматек`,
      logoSrc: `ormatek.svg`,
      synonyms: ['орматек', 'ormatek'],
      description: `Товары для сна`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/54`,
      path: `M1492.92,751.14v66.25l-99.27,0V723L1444,751.14Z`,
    },
    {
      id: 225,
      title: `Папа Карло`,
      logoSrc: `papa-karlo.svg`,
      synonyms: ['папа карло', 'кухня', 'papa karlo'],
      description: `Центр кухни`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/55`,
      path: `M1527.53,751.14v66.24h-34.61V751.14Z`,
    },
    {
      id: 226,
      title: `Еврочехол`,
      logoSrc: `evrochehol.svg`,
      synonyms: ['tdhjxt[jk', 'евро чехол', 'еврочехол'],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/46`,
      path: `M1126.5,729.5c0-1.59-.08-3.15-.23-4.7l20.9-20.8v52.44h-28.56A49.73,49.73,0,0,0,1126.5,729.5Z`,
    },
    {
      id: 227,
      title: `Profcosmo`,
      logoSrc: `profcosmo.svg`,
      synonyms: [
        'profcosmo',
        'профкосмо',
        'профессиональная косметика',
        'инструменты для парикмахеров',
        'инструменты для визажистов',
        'инструменты для мастеров маникюра',
        'средства для укладки',
        'косметика',
      ],
      description: `Профессиональная косметика`,
      discount: new Set(),
      category: new Set([categoryFilter[`Парфюмерия и косметика`]]),
      audience: new Set(),
      shopURL: `/shop/101`,
      path: `M1092.56,682.15V641.87h27.85l0,19-22.16,23.62a50.28,50.28,0,0,0-5.67-2.32V641.87`,
    },
    {
      id: 228,
      title: `ОБЪЕКТИВ`,
      logoSrc: `obektiv.svg`,
      synonyms: ['объектив', 'фотосалон'],
      description: `Фотосалон`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/107`,
      path: `M1558.85,751.14v66.23h-31.32V751.14Z`,
    },
    {
      id: 229,
      title: `Acoola`,
      logoSrc: `acoola.svg`,
      synonyms: [
        'frekf',
        'акула',
        'акулла',
        'аколла',
        'акола',
        'acoola',
        'детская одежда',
        'одежда для детей',
        'школьная форма',
        'детские платья',
        'детские костюмы',
      ],
      description: `Модная одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/12`,
      path: `M1618.73,817.35l-59.88,0V751.14h59.88Z`,
    },
    {
      id: 230,
      title: `Timbers`,
      logoSrc: `timbers.svg`,
      synonyms: ['timbers', 'тимберс', 'таймберс', 'мебель из массива'],
      description: `Мебель из массива`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/43`,
      path: `M1300,817.46V670.67l43.42,24.26V817.45Z`,
    },
    {
      id: 231,
      title: `Респект`,
      logoSrc: `respekt.svg`,
      synonyms: ['htcgtrn', 'респект', 'риспект'],
      description: `Мягкая мебель`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/57`,
      path: `M1343.42,817.45V694.93L1393.65,723v94.44ZM1300,624.57l53,29.75v-44.4h-53Zm77-14.65v57.87l54,30.32V609.92Z`,
    },
    {
      id: 232,
      title: `SUNLIGHT`,
      logoSrc: `sunlight.svg`,
      synonyms: ['Санлайт', 'Sunlait', 'Sunlight', 'cfykfqn'],
      description: `Ювелирные изделия`,
      discount: new Set(),
      category: new Set([categoryFilter[`Ювелирные изделия`]]),
      audience: new Set(),
      shopURL: `/shop/119`,
      path: `M1032.86,705.1H998.72a81.24,81.24,0,0,1,8.28-18.17V641.87h85.56v40.28a50,50,0,0,0-59.7,23Z`,
    },
    {
      id: 233,
      title: `CHESTER RESTOBAR`,
      logoSrc: `chester-restobar.svg`,
      synonyms: ['честер', 'chester', 'chester restobar', 'честор'],
      description: `Ресторан`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/62`,
      path: `M1193.5,756.44V817.5s-41.43,18-78.6,29.06L1104.6,806a81.68,81.68,0,0,1-59.08-1.13V787.26l11.66-11.63h0a50,50,0,0,0,61.42-19.19Z`,
    },
    {
      id: 234,
      title: `FISSMAN`,
      logoSrc: `fissman.svg`,
      synonyms: [
        'фисмэн',
        'физмэн',
        'fissman',
        'fiszman',
        'fissmen',
        'abccv\'y',
      ],
      description: `Посуда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Товары для дома`]]),
      audience: new Set(),
      shopURL: `/shop/50`,
      path: `M1029.09,745.39v0l-12.76,12.68h-16.16a81.75,81.75,0,0,1-1.45-53h34.14a50,50,0,0,0-3.77,40.29Z`,
    },
    {
      id: 235,
      title: `TOY.RU`,
      logoSrc: `toyru.svg`,
      synonyms: [
        'toy.ru',
        'той',
        'игрушки',
        'ещн',
        'товары для детей',
        'детские товары',
      ],
      description: `Детские товары и игрушки`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/129`,
      path: `M1682.89,751.14h68V817.3l-68,0Z`,
    },
    {
      id: 236,
      title: `Morojko`,
      logoSrc: `morojko.svg`,
      synonyms: [
        'морожко',
        'морозко',
        'vjhj;rj',
        'vjhjprj',
        'мороженное',
        'мороженое ',
      ],
      description: `Morojko`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/61`,
      path: `M1140.41,641.87h-20v-26h20Z`,
    },
    {
      id: 237,
      title: `OBI`,
      logoSrc: `obi.svg`,
      synonyms: [
        'j,b',
        'оби',
        'строительный',
        'обби',
        'щиш',
        'obi',
        'товары для дома',
      ],
      description: `Строительный гипермаркет`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Товары для дома`],
        categoryFilter[`Хобби, книги, канцтовары`],
      ]),
      audience: new Set(),
      shopURL: `/shop/92`,
      path: `M1031,1V592H819v61H725v22H605V653H511V592H1V1Z`,
    },
    {
      id: 238,
      title: `Burger Club Loft`,
      logoSrc: `burgerclub.svg`,
      synonyms: ['burger club loft', 'burger', 'бургерная', 'черные бургеры'],
      description: `Сеть бургерных`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/65`,
      path: `M1031,548h90v44h-90Z`,
    },
    {
      id: 239,
      title: `Леонардо`,
      logoSrc: `leonardo.svg`,
      synonyms: [
        'леонардо',
        'ktjyfhlj',
        'хобби',
        'товары для рукоделия',
        'товары для дома',
        'творчество',
        'товары для творчества',
      ],
      description: `Хобби-гипермаркет`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Товары для дома`],
        categoryFilter[`Хобби, книги, канцтовары`],
      ]),
      audience: new Set(),
      shopURL: `/shop/172`,
      path: `M1031,284h90V548h-90Z`,
    },
    {
      id: 240,
      title: `Детский мир`,
      logoSrc: `detmir.svg`,
      synonyms: [
        'детскиймир',
        'игрушки',
        'детская одежда',
        'одежда для детей',
        'детские товары',
        'детская обувь',
      ],
      description: `Для детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/155`,
      path: `M1262,1V261H1121v23h-90V1Z`,
    },
    {
      id: 241,
      title: `М.Видео`,
      logoSrc: `mvideo.svg`,
      synonyms: [
        'mvideo',
        'мвидиа',
        'м видео',
        'мвидео',
        'м_видео',
        'м-видео',
        'мвидио',
        'техника',
        'бытовая техника',
        'электроника',
        'телевизор',
        'смартфон',
        'vdbltj',
      ],
      description: `Магазин бытовой техники и электроники`,
      discount: new Set(),
      category: new Set([categoryFilter[`Бытовая техника, электроника`]]),
      audience: new Set(),
      shopURL: `/shop/178`,
      path: `M1566,1V311H1392v18H1262V1Z`,
    },
    {
      id: 242,
      title: `DMI Дятьково Кухни`,
      logoSrc: `dyatkovo-kitchen.svg`,
      synonyms: ['дятьково', 'dmi', 'кухни', 'дми'],
      description: `Кухни`,
      discount: new Set(),
      category: new Set([categoryFilter['Мебель Холл']]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/38`,
      path: `M1392,329V461h-64V329Z`,
    },
    {
      id: 243,
      title: `DMI Дятьково`,
      logoSrc: `dyatkovo.svg`,
      synonyms: ['lznmrjdj', 'дятьковомебель', 'мебель', 'диэмай', 'диемай'],
      description: `Мебель`,
      discount: new Set(),
      category: new Set([categoryFilter['Мебель Холл']]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/36`,
      path: `M1328,329V461h-66V329Z`,
    },
    {
      id: 244,
      title: `Мебель Черноземья`,
      logoSrc: `mche.svg`,
      synonyms: ['мебель черноземья', 'xthyjptvmt', 'vt,tkm'],
      description: `Фирменные салоны мебели`,
      discount: new Set(),
      category: new Set([categoryFilter['Мебель Холл']]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/53`,
      path: `M1507.5,311H1566V461h-58.5Z`,
    },
    {
      id: 245,
      title: `Шатура`,
      logoSrc: `shatura.svg`,
      synonyms: ['шатура', 'ifnehf'],
      description: `Мебельная компания`,
      discount: new Set(),
      category: new Set([categoryFilter['Мебель Холл']]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/60`,
      path: `M1449.5,311V461H1392V311Z`,
    },
    {
      id: 246,
      title: `Ангстрем`,
      logoSrc: `angstrem.svg`,
      synonyms: ['ангстрем'],
      description: `Мебельная компания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/44`,
      path: `M1507.5,311V461h-58V311Z`,
    },
    {
      id: 247,
      title: `Gulliver`,
      logoSrc: `gulliver.svg`,
      synonyms: [
        'gulliver',
        'гулливер',
        'гуливер',
        'одежда для детей',
        'детская одежда',
        'школьная форма',
        'игрушки',
      ],
      description: `Детская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/54`,
      path: `M2422,427.7,2396,461v0h-46.5V410H2422Z`,
    },
    {
      id: 248,
      title: `Mustang Jeans`,
      logoSrc: `mustang-jeans.svg`,
      synonyms: [
        'mustang jeans',
        'мустанг джинс',
        'джинсы',
        'футболки',
        'рубашки',
        'кожаные куртки',
        'юбки',
        'женская одежда',
        'мужская одежда',
      ],
      description: `Женская и мужская одежда, джинсы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
      ]),
      shopURL: `/shop/89`,
      path: `M1932,410h68.23L1982,461h-50Z`,
    },
    {
      id: 249,
      title: `Технопарк`,
      logoSrc: `technopark.svg`,
      synonyms: [
        'технопарк',
        'бытовая техника и электроника',
        'техно',
        'техника',
        'телевизоры',
      ],
      description: `Бытовая техника и электроника`,
      discount: new Set(),
      category: new Set([categoryFilter[`Бытовая техника, электроника`]]),
      audience: new Set(),
      shopURL: `/shop/205`,
      path: `M1799,196V461H1667V413H1566V196Z`,
    },
    {
      id: 250,
      title: `ProfilDoors`,
      logoSrc: `profildoors.svg`,
      synonyms: [
        'profildoors',
        'двери',
        'межкомнатные двери',
        'перегородки',
        'кухни',
        'шкафы',
        'мебель',
      ],
      description: `Центр интерьерных решений`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/41`,
      path: `M1667,413v48h-62V413Z`,
    },
    {
      id: 251,
      title: `Стальная линия`,
      logoSrc: `stalnaya-liniya.svg`,
      synonyms: [
        'стальная линия',
        'линия',
        'двери',
        'входные двери',
        'белорусские двери',
      ],
      description: `Входные двери`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/58`,
      path: `M1605,413v48h-39V413Z`,
    },
    {
      id: 252,
      title: `CCC Shoes&Bags`,
      logoSrc: `ccc.svg`,
      synonyms: ['ccc', 'ссс', 'обувь', 'аксессуары', 'cc'],
      description: `Обувь и аксессуары`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Обувь, сумки, кожгалантерея`],
        categoryFilter[`Детские товары и одежда`],
      ]),
      audience: new Set(),
      shopURL: `/shop/200`,
      path: `M1900,410v51H1799V196h101V410Z`,
    },
    {
      id: 253,
      title: `ПАНОРАМА`,
      logoSrc: `panorama.svg`,
      synonyms: ['панорама', 'сеть кинотеатров', 'кино', 'кинозал'],
      description: `Сеть кинотеатров`,
      discount: new Set(),
      category: new Set(),
      audience: new Set(),
      shopURL: `/film`,
      path: `M2349.5,410H2144.71l-.21-.5.21.5H2048V351H1900V196h522V410Z`,
    },
    {
      id: 254,
      title: `Black Star Burger`,
      logoSrc: `blackstarburger.svg`,
      synonyms: ['Black Star Burger', 'блэк стар бургер'],
      description: `Бургеры от профессиональных поваров`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/90`,
      path: `M2048,351v59H1900V351Z`,
    },
    {
      id: 255,
      title: `LN Code`,
      logoSrc: `ln-code.svg`,
      synonyms: [
        'ln code',
        'ln',
        'лия назарова',
        'лия',
        'лн код',
        'эл эн',
        'код',
        'code',
      ],
      description: `Дизайнерская одежда и аксессуары`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/71`,
      path: `M1932,410v51h-32V410Z`,
    },
    {
      id: 256,
      title: `Дочки-Сыночки`,
      logoSrc: `dochkisinochki.svg`,
      synonyms: [
        'дочки-сыночки',
        'дочкисыночки',
        'одежда',
        'обувь',
        'игрушки',
        'трансформеры',
        'коляски',
        'кроватки',
        'подгузники',
      ],
      description: `Для детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/157`,
      path: `M2599,196V477h-36v61H2396V461l26-33.3V196Z`,
    },
    {
      id: 257,
      title: `Game Zone`,
      logoSrc: `game-zone.svg`,
      synonyms: [
        'game zone',
        'гейм зон',
        'гейм зона',
        'видеоигры',
        'консоли',
        'игровые',
        'роботы',
      ],
      description: `Видеоигры, консоли, аксессуары к ним`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/216`,
      path: `M2349.5,410v51h-31V410Z`,
    },
    {
      id: 258,
      title: `Button Blue`,
      logoSrc: `button-blue.svg`,
      synonyms: [
        'button blue',
        'баттон блу',
        'детская одежда',
        'одежда для детей',
        'одежда для ребенка',
      ],
      description: `Детская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/30`,
      path: `M2245,410v51h-47V410Z`,
    },
    {
      id: 259,
      title: `КАРАМЕЛЬ.КI boys`,
      logoSrc: `karamelki-boys.svg`,
      synonyms: ['карамельки', 'детская одежда', 'детская обувь'],
      description: `Детская одежда`,
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/163`,
      path: `M2198,410v51h-32l-21.29-51H2198Z`,
    },
    {
      id: 260,
      title: `Весёлая расческа`,
      logoSrc: `vesyolaya-rascheska.svg`,
      synonyms: ['весёлая расческа'],
      description: `Детская студия красоты`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/98`,
      path: `M2245,410h45v51h-45Z`,
    },
    {
      id: 261,
      title: `Сувениры. Антиквариат`,
      logoSrc: `suveniry-antikvariat.svg`,
      synonyms: ['сувениры антиквариат'],
      description: `Магазин сувениров`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/201`,
      path: `M2146,669v34l-50-29v-5Z`,
    },
    {
      id: 262,
      title: `Pegas`,
      logoSrc: `pegast.svg`,
      synonyms: ['pegas', 'туризм', 'турагентство'],
      description: `Туристические агентства`,
      discount: new Set(),
      category: new Set([categoryFilter[`Туристические агентства`]]),
      audience: new Set(),
      shopURL: `/shop/217`,
      path: `M2122,573h-26V555.75a75.77,75.77,0,0,0,26-13.84Z`,
    },
    {
      id: 263,
      title: `Missha`,
      logoSrc: `missha.svg`,
      synonyms: [
        'косметика',
        'missha',
        'корейская косметика',
        'уход за кожей',
        'средства для укладки',
        'шампуни',
        'помада',
        'парфюм',
        'духи',
      ],
      description: `Корейская косметика`,
      discount: new Set(),
      category: new Set([categoryFilter[`Парфюмерия и косметика`]]),
      audience: new Set(),
      shopURL: `/shop/84`,
      path: `M2136.3,526.5h9.7V573h-24V541.91A76.11,76.11,0,0,0,2136.3,526.5Z`,
    },
    {
      id: 264,
      title: `Pelican Kids`,
      logoSrc: `pelican-kids.svg`,
      synonyms: ['pelican kids', 'пеликан', 'детское', 'дети', 'кидс'],
      description: `Детская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Товары дял детей`]]),
      shopURL: `/shop/100`,
      path: `M2198,573V507h51v66Z`,
    },
    {
      id: 265,
      title: `Zenden`,
      logoSrc: `zenden.svg`,
      synonyms: [
        'зенден',
        'zenden',
        'обувь',
        'женская обувь',
        'мужская обувь',
        'детская обувь',
        'сумки',
        'туфли',
        'ботинки',
        'сапоги',
        'кошельки',
        'стельки',
      ],
      description: `Практичная недорогая обувь`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Обувь, сумки, кожгалантерея`],
        categoryFilter[`Детские товары и одежда`],
      ]),
      audience: new Set(),
      shopURL: `/shop/140`,
      path: `M2198,573V703h-52V507.32c0-.1.07-.21.11-.32H2198Z`,
    },
    {
      id: 266,
      title: `adidas`,
      logoSrc: `adidas.svg`,
      synonyms: ['адидас', 'абибас', 'adibas', 'flblfc', 'спорт', 'жизнь'],
      description: `Спортивные товары, одежда, обувь`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Спортивные товары и одежда`],
        categoryFilter[`Детские товары и одежда`],
      ]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
        audienceFilter[`Для детей`],
      ]),
      shopURL: `/shop/5`,
      path: `M2299,573h49v65h-78v65h-72V573h101Z`,
    },
    {
      id: 267,
      status: false,
      title: `STIL.НЯШКИ`,
      logoSrc: `stilnyashka.svg`,
      synonyms: [
        'стильняшка',
        'stil.няшка',
        'стиль',
        'детская дизайнерская одежда',
        'stil',
        'няшки',
      ],
      description: `Детская одежда`,
      discount: new Set(),
      category: new Set(),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/116`,
      path: `M2348,507v66h-49V507Z`,
    },
    {
      id: 268,
      title: `КАРАМЕЛЬ.KI`,
      logoSrc: `karamelki.svg`,
      synonyms: ['карамельки', 'детская одежда', 'детская обувь'],
      description: `Детская одежда и обувь`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/162`,
      path: `M2249,573V507h50v66Z`,
    },
    {
      id: 269,
      title: `GrossHaus`,
      logoSrc: `grosshaus.svg`,
      synonyms: ['grosshaus', 'gros', 'гросхауз', 'гросхаус'],
      description: `Товары для офиса и школы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Хобби, книги, канцтовары`]]),
      audience: new Set(),
      shopURL: `/shop/53`,
      path: `M2270,638h78v32.5h-78Z`,
    },
    {
      id: 270,
      title: `Takeshy Kurosawa`,
      logoSrc: `takeshykurosawa.svg`,
      synonyms: [
        'takeshy kurosawa',
        'такеша',
        'такэша',
        'куросава',
        'курасава',
        'nfrtib',
        'такеши',
        'такеши куросава',
      ],
      description: `Женская и мужская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
      ]),
      shopURL: `/shop/121`,
      path: `M2300.5,670.5V703H2270V670.5Z`,
    },
    {
      id: 271,
      title: `MYBOX`,
      logoSrc: `mybox.svg`,
      synonyms: ['mybox', 'Суши', 'Японская', 'майбокс', 'май бокс'],
      description: `Японская кухня, суши`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/81`,
      path: `M2300.5,670.5H2348V703h-47.5Z`,
    },
    {
      id: 272,
      title: `Kovalina`,
      logoSrc: `kovalina.svg`,
      synonyms: [
        'kovalina',
        'ковалина',
        'портфели',
        'сумки',
        'чемоданы',
        'аксессуары',
        'кожгалантерея',
      ],
      description: `Портфели, сумки, чемоданы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Обувь, сумки, кожгалантерея`]]),
      audience: new Set(),
      shopURL: `/shop/64`,
      path: `M2146,637.5h-50V573h50Z`,
    },
    {
      id: 273,
      title: `ANTIGA`,
      logoSrc: `antiga.svg`,
      synonyms: ['антига', 'antiga', 'ант', 'женская одежда'],
      description: `Для женщин`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/7`,
      path: `M2146,669h-50V637.5h50Z`,
    },
    {
      id: 274,
      title: `Лепрекон`,
      logoSrc: `leprekon.svg`,
      synonyms: [
        'лепрекон',
        'липрекон',
        'leprekon',
        'настольные игры',
        'игры',
        'ktghtrjy',
      ],
      description: `Настольные игры`,
      discount: new Set(),
      category: new Set([categoryFilter[`Хобби, книги, канцтовары`]]),
      audience: new Set(),
      shopURL: `/shop/173`,
      path: `M2000,669h50.22v6.09L2000,703Z`,
    },
    {
      id: 275,
      title: `ШОУ РУМ №1`,
      logoSrc: `shou-rum.svg`,
      synonyms: [
        'шоу рум',
        'женская одежда',
        'одежда',
        'платья',
        'юбки',
        'брюки',
        'блузы',
        'молодежная одежда',
        'аксессуары',
      ],
      description: `Женская, молодежная одежда и аксессуары`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/213`,
      path: `M2000,573V529.83h14.17a76.41,76.41,0,0,0,10,10.55V573Z`,
    },
    {
      id: 276,
      title: `LONDON STYLE`,
      logoSrc: `london-style.svg`,
      synonyms: [
        'london style',
        'london',
        'лондон',
        'londonstyle32',
        'lonsdale',
        'gifted',
        'sigma',
        'affex',
      ],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set(),
      shopURL: `/shop/74`,
      path: `M2000,637.5h50.22V669H2000Z`,
    },
    {
      id: 277,
      title: `Императорский фарфор`,
      logoSrc: `ipm.svg`,
      synonyms: ['императорский фарфор'],
      description: `Изделия из фарфора`,
      discount: new Set(),
      category: new Set([categoryFilter[`Товары для дома`]]),
      audience: new Set(),
      shopURL: `/shop/160`,
      path: `M2000,604.5h50.22v33H2000Z`,
    },
    {
      id: 278,
      title: `the SAEM`,
      logoSrc: `thesaem.svg`,
      synonyms: [
        'косметика',
        'the saem',
        'корейская косметика',
        'уход за кожей',
        'средства для укладки',
        'шампуни',
        'помада',
        'парфюм',
        'духи',
        'саем',
      ],
      description: `Корейская косметика`,
      discount: new Set(),
      category: new Set([categoryFilter[`Парфюмерия и косметика`]]),
      audience: new Set(),
      shopURL: `/shop/127`,
      path: `M2024.2,540.38a75.63,75.63,0,0,0,26,14.8V573h-26Z`,
    },
    {
      id: 279,
      title: `Мальцов`,
      logoSrc: `malcov.svg`,
      synonyms: ['мальцов', 'хрусталь', 'дятьковский'],
      description: `Изделия из хрусталя`,
      discount: new Set(),
      category: new Set([categoryFilter[`Товары для дома`]]),
      audience: new Set(),
      shopURL: `/shop/176`,
      path: `M2024.2,573h26v31.5H2000V573Z`,
    },
    {
      id: 280,
      title: `Буду мамой`,
      logoSrc: `budumamoy.svg`,
      synonyms: [
        'буду мамой',
        ',ele vfvjq',
        'для будущих мам',
        'одежда для мам',
        'одежда для беременных',
        'для кормящих мам',
        'аксессуары для беременных',
      ],
      description: `Одежда для будущих мам`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/150`,
      path: `M1849.13,573H1799V506h50.13Z`,
    },
    {
      id: 281,
      title: `Mavi`,
      logoSrc: `mavi.svg`,
      synonyms: [
        'mavi',
        'mavi',
        'мави',
        'джинсы',
        'свитер',
        'кофта',
        'блузка',
        'верхняя одежда',
        'толстовки',
        'нижнее белье',
        'обувь',
        'головные уборы',
        'сумки',
        'женская одежда',
        'мужская одежда',
      ],
      description: `Женская и мужская одежда, джинсы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
      ]),
      shopURL: `/shop/80`,
      path: `M1849.13,573V506h50.37v81.94h-50.37Z`,
    },
    {
      id: 282,
      title: `Читай-город`,
      logoSrc: `chitai-gorod.svg`,
      synonyms: ['читай-город'],
      description: `Книги и многое другое`,
      discount: new Set(),
      category: new Set([categoryFilter[`Хобби, книги, канцтовары`]]),
      audience: new Set(),
      shopURL: `/shop/210`,
      path: `M1899.5,587.94V506h51.18v81.94Z`,
    },
    {
      id: 283,
      title: `Venzano`,
      logoSrc: `venzano.svg`,
      synonyms: [
        'вензано',
        'костюмы',
        'venzano',
        'деловая одежда',
        'офисная одежда',
        'одежда',
        'мужская одежда',
        'одежда для мужчин',
        'брюки',
        'сорочки',
        'рубашки',
        'пиджаки',
      ],
      description: `Мужская деловая одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для мужчин`]]),
      shopURL: `/shop/133`,
      path: `M1824.49,670.29H1799V573h50.13v97.29Z`,
    },
    {
      id: 284,
      title: `Alena Goretskaya (Алена Горецкая)`,
      logoSrc: `alena-goretskaya.svg`,
      synonyms: [
        'алена горетская',
        'горецкая',
        'алёна',
        'fktyf ujhtncrfz',
        'ujhtwrfz',
      ],
      description: `Стильная женская одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([audienceFilter[`Для женщин`]]),
      shopURL: `/shop/6`,
      path: `M1824.49,670.29V703H1799V670.29Z`,
    },
    {
      id: 286,
      title: `ТВОЕ`,
      logoSrc: `tvoe.svg`,
      synonyms: ['твое'],
      description: `Молодежная одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
      ]),
      shopURL: `/shop/203`,
      path: `M1899.5,587.94V703h-50.37V587.94Z`,
    },
    {
      id: 287,
      title: `Роскошь с пеленок`,
      logoSrc: `roskosh-s-pelenok.svg`,
      synonyms: [
        'роскошь с пеленок',
        'одежда для новорожденных',
        'детская одежда',
        'конверты на выписку',
      ],
      description: `Для детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/193`,
      path: `M1849.13,670.29V703h-24.64V670.29Z`,
    },
    {
      id: 288,
      title: `Другие подарки`,
      logoSrc: `drugie-podarki.svg`,
      synonyms: ['другие подарки'],
      description: `Необычные подарки, сувениры.`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/158`,
      path: `M2000,669v34h-34V669Z`,
    },
    {
      id: 289,
      title: `Ltb`,
      logoSrc: `ltb.svg`,
      synonyms: ['ltb', 'джинсы'],
      description: `Модная джинсовая одежда для всей семьи`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
      ]),
      shopURL: `/shop/75`,
      path: `M1950.68,587.94V506H2000v98.5h-49.32Z`,
    },
    {
      id: 290,
      title: `100 столов`,
      logoSrc: `100-stolov.svg`,
      synonyms: ['сто столов', '100 столов', 'cnj cnjkjd', 'столов', 'сто'],
      description: `Мебельная компания`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/33`,
      path: `M1353,506v79h-89V506Z`,
    },
    {
      id: 293,
      title: `Лидер`,
      logoSrc: `lider.svg`,
      synonyms: ['лидер', 'лидир', 'kblth'],
      description: `Мебельная фабрика`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/51`,
      path: `M1485,609.92V643h-54V609.92Z`,
    },
    {
      id: 294,
      title: `Gray Kardinal`,
      logoSrc: `gray-kardinal.svg`,
      synonyms: ['gray kardinal'],
      description: `Дизайн-студия элитной мебели`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/39`,
      path: `M1431,643h54v62h-41.72L1431,698.11Z`,
    },
    {
      id: 295,
      title: `МЕБЕЛЬ-МОСКВА`,
      logoSrc: `mebel-moskva.svg`,
      synonyms: ['мебель москва', 'мебельмосква', 'vt,tkm vjcrdf'],
      description: `Фабрика мебели`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/52`,
      path: `M1564.66,647.05H1507.5V589.2h57.16Z`,
    },
    {
      id: 296,
      title: `Кухни Катюша`,
      logoSrc: `kuhni-katyusha.svg`,
      synonyms: ['кухни катюша', 'кухни', 'катюша', 'кухонный гарнитур'],
      description: `Кухонные гарнитуры`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/48`,
      path: `M1564.66,589.2H1507.5V544h57.16V589.2Z`,
    },
    {
      id: 297,
      title: `ECOLA`,
      logoSrc: `ecola.svg`,
      synonyms: [
        'экола',
        'есоla',
        'светоник',
        'свет',
        'лампы',
        'светодиодные',
        'энергосберегающие',
      ],
      description: `Энергосберегающие и светодиодные лампы и светильники`,
      discount: new Set(),
      category: new Set([categoryFilter[`Товары для дома`]]),
      audience: new Set(),
      shopURL: `/shop/45`,
      path: `M1564.66,544V506h39.67v53.89h-39.67Z`,
    },
    {
      id: 298,
      title: `Кухни Трио`,
      logoSrc: `kuhni-trio.svg`,
      synonyms: ['nhbj', 'кухни трио', 'трио', 'кухни'],
      description: `Кухни`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/49`,
      path: `M1564.66,544H1507.5V506h57.16Z`,
    },
    {
      id: 299,
      title: `MOON`,
      logoSrc: `moon.svg`,
      synonyms: ['moon'],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/40`,
      path: `M1564.66,647.05v58H1507.5v-58Z`,
    },
    {
      id: 2100,
      title: `O'STIN`,
      logoSrc: `ostin.svg`,
      synonyms: ['одежда', 'сумки', 'аксессуары', 'остин', 'ostin', 'остин'],
      description: `Женская и мужская одежда, аксессуары`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Одежда и аксессуары`],
        categoryFilter[`Детские товары и одежда`],
        categoryFilter[`Аксессуары и часы`],
      ]),
      audience: new Set([
        audienceFilter[`Для мужчин`],
        audienceFilter[`Для женщин`],
        audienceFilter[`Для детей`],
      ]),
      shopURL: `/shop/95`,
      path: `M1701.59,603.85h48.91v66.44h-48.91V705H1564.66V559.89h136.93Z`,
    },
    {
      id: 2101,
      title: `Лазурит`,
      logoSrc: `lazurit.svg`,
      synonyms: [
        'лазурит',
        'lazurit',
        'мебель',
        'мягкая мебель',
        'корпусная',
        'лазур',
        'kfpehbn',
      ],
      description: `Мягкая и корпусная мебель`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/50`,
      path: `M1750.5,506v33.89h-33v20h-62.4V506Z`,
    },
    {
      id: 2102,
      title: `Svyatnyh`,
      logoSrc: `svyatnyh.svg`,
      synonyms: ['svyatnyh', 'костюм', 'рубашка', 'пальто', 'святных'],
      description: `Мужская деловая одежда`,
      discount: new Set(),
      category: new Set([
        categoryFilter[`Одежда и аксессуары`],
        categoryFilter[`Аксессуары и часы`],
      ]),
      audience: new Set([audienceFilter[`Для мужчин`]]),
      shopURL: `/shop/120`,
      path: `M1701.59,670.29h48.91V705h-48.91Z`,
    },
    {
      id: 2103,
      title: `BEL POL`,
      logoSrc: `belpol.svg`,
      synonyms: [
        'bel pol',
        'бель-поль',
        'домашний текстиль',
        'одеяла',
        'подушки',
        'пух',
      ],
      description: `Домашний текстиль`,
      discount: new Set(),
      category: new Set([categoryFilter[`Товары для дома`]]),
      audience: new Set(),
      shopURL: `/shop/222`,
      path: `M1604.33,559.89V506h50.78v53.89Z`,
    },
    {
      id: 2104,
      title: `NAIL32`,
      logoSrc: `nail32.svg`,
      synonyms: [
        'нэйл 32',
        'nail',
        'найл',
        'все для ногтей',
        'материалы и инструменты для ногтей',
      ],
      description: `Материалы и инструменты для профессионалов`,
      discount: new Set(),
      category: new Set([categoryFilter[`Парфюмерия и косметика`]]),
      audience: new Set(),
      shopURL: `/shop/90`,
      path: `M1717.51,539.89h33v20h-33Z`,
    },
    {
      id: 2105,
      title: `ТРИЭС`,
      logoSrc: `tries.svg`,
      synonyms: ['dfiltym', 'dfi ltym', 'ваш-день'],
      description: `Фабрика мягкой и корпусной мебели`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/59`,
      path: `M1431,532h54v53h-54Z`,
    },
    {
      id: 2106,
      title: `AERO`,
      logoSrc: `aero.svg`,
      synonyms: [
        'аэро',
        'столбери',
        'столы и стулья',
        'cnjk ,thb',
        'f\'hj',
        'fehj',
        'аеро',
      ],
      description: `Столы и стулья`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/34`,
      path: `M1431,532v53h-54V506h54Z`,
    },
    {
      id: 2107,
      title: `Добрый стиль`,
      logoSrc: `dobryj-stil.svg`,
      synonyms: ['добрый стиль', 'мягкая мебель', 'добрый'],
      description: `Мебель`,
      discount: new Set(),
      category: new Set([categoryFilter[`Мебель Холл`]]),
      audience: new Set(),
      shopURL: `/dynamic/mebel-hall/45`,
      path: `M1485,506v26h-54V506Z`,
    },
    {
      id: 2108,
      title: `Вкусная помощь`,
      logoSrc: ``,
      synonyms: [
        'вкусная помощь',
        'вкусная',
        'drecyfz gjvjom',
        'кондитерская помощь',
        'кондитерская',
      ],
      description: `Кондитерские изделия`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/151`,
      path: `M1671,743h-16V727h16Z`,
    },
    {
      id: 2109,
      title: `Pedant.ru`,
      logoSrc: ``,
      synonyms: ['ремонт смартфонов', 'pedant', 'ремонт', 'смартфоны'],
      description: `Ремонт смартфонов`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/93`,
      path: `M1600,743h-16V727h16Z`,
    },
    {
      id: 2110,
      title: `Веселый паровозик`,
      logoSrc: ``,
      synonyms: ['веселый паровозик'],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Развлечения`]]),
      audience: new Set(),
      shopURL: `/dynamic/entertainment/7`,
      path: `M1236,587h-16V571h16Z`,
    },
    {
      id: 2112,
      title: `Чистомир`,
      logoSrc: ``,
      synonyms: [
        'Чистомир',
        'клининг',
        'уборка квартир',
        'чистка квартир',
        'генеральная уборка',
        'чистящие средства',
        'моющие средства',
        'чистить',
      ],
      description: `Группа клининговых компаний`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/110`,
      path: `M1658,491h-16V475h16Z`,
    },
    {
      id: 2113,
      title: `Street Studio`,
      logoSrc: ``,
      synonyms: ['Street', 'Studio', 'СтриитСтудио'],
      description: `Студия печати`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/shop/118`,
      path: `M1783,659v16h-16V659Z`,
    },
    {
      id: 2114,
      title: `31 ВЕК`,
      logoSrc: ``,
      synonyms: ['31 dtr', '21 век', '31й век', 'сувениры', 'cedtybhs'],
      description: `Подарки из будущего, сувениры`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/3`,
      path: `M2081,580.75v16h-16v-16Z`,
    },
    {
      id: 2115,
      title: `Фотокиоск INSTA PHOTO`,
      logoSrc: ``,
      synonyms: ['инст', 'киоск', 'фото', 'инстаграм'],
      description: `Печать фотографий из Instagram`,
      discount: new Set(),
      category: new Set([categoryFilter[`Другое`]]),
      audience: new Set(),
      shopURL: `/shop/206`,
      path: `M2014,515.83v14h-14v-14Z`,
    },
    {
      id: 2116,
      title: `Vinegret`,
      logoSrc: ``,
      synonyms: [
        'vinegret',
        'винегрет',
        'аксессуары',
        'кожа',
        'кожгалантерея',
        'винигрет',
        'винт',
        'vine',
        'vini',
        'сумки',
        'клатчи',
        'портмоне',
      ],
      description: `Кожгалантерея`,
      discount: new Set(),
      category: new Set([categoryFilter[`Обувь, сумки, кожгалантерея`]]),
      audience: new Set(),
      shopURL: `/shop/134`,
      path: `M1956,491h-16V475h16Z`,
    },
    {
      id: 2117,
      title: `LEPIN`,
      logoSrc: ``,
      synonyms: ['лего', 'лепин', 'lego-lepin', 'lepin'],
      description: `Детские конструкторы`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/67`,
      path: `M2206,492h-16V476h16Z`,
    },
    {
      id: 2118,
      title: `Массажные кресла`,
      logoSrc: ``,
      synonyms: ['массажные кресла', 'массаж', 'кресла'],
      description: `Остров релаксации`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/102`,
      path: `M2253,492h-16V476h16Z`,
    },
    {
      id: 2119,
      title: `KRUTOYS`,
      logoSrc: ``,
      synonyms: [
        'крутойс',
        'krutoys',
        'krutoys',
        'круtoys',
        'радиоуправляемые игрушки',
        'игрушки',
        'квадрокоптеры',
        'роботы',
        'трансформеры',
        'игрушки на пульте управления',
      ],
      description: `Для детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/65`,
      path: `M2379.5,515v16h-16V515Z`,
    },
    {
      id: 2120,
      title: `JUICY FRUIT`,
      logoSrc: ``,
      synonyms: ['juicy fruit', 'джуси фруйт', 'джуси фрут', 'джуси фрукт'],
      description: `Фреш-бар`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/75`,
      path: `M2379.5,612.5v16h-16v-16Z`,
    },
    {
      id: 2121,
      title: `КОФЕ ХАУЗ`,
      logoSrc: ``,
      synonyms: ['кофе хауз', 'кофе', 'кофейня'],
      description: `Кофе и десерты`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/4`,
      path: `M2393,681v16h-16V681Z`,
    },
    {
      id: 2122,
      title: `Море желаний`,
      logoSrc: ``,
      synonyms: ['море желаний', 'рыбки', 'vjht ;tkfybq'],
      description: ``,
      discount: new Set(),
      category: new Set([categoryFilter[`Другое`]]),
      audience: new Set(),
      shopURL: `/shop/182`,
      path: `M2395,589v16h-12V589Z`,
    },
    {
      id: 2123,
      title: `Крутецкие игрушки`,
      logoSrc: ``,
      synonyms: [
        'крутецкие игрушки',
        'игрушки',
        'автоматы игрушек',
        'автомат по продаже игрушек',
        'детские игрушки',
        'тачки',
        'лизун',
        'фиксики',
        'вспыш',
        'барбоскины',
        'крутецкие',
        'игрушки',
        'rhentwrfz',
        'свинка пеппи',
        'щенячий патруль',
        'миньоны',
        'робокоп',
        'поли',
      ],
      description: `Для детей`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары`]]),
      audience: new Set(),
      shopURL: `/shop/169`,
      path: `M2395,569v16h-12V569Z`,
    },
    {
      id: 2124,
      title: `ArtHobby`,
      logoSrc: ``,
      synonyms: [
        'ArtHobby',
        'артхобби',
        'ahn[j,,b',
        'арт-хобби',
        'артхоби',
        'картинки по номерам',
        'рисовать',
        'картины',
      ],
      description: `Картины по номерам`,
      discount: new Set(),
      category: new Set([categoryFilter[`Подарки, сувениры`]]),
      audience: new Set(),
      shopURL: `/shop/21`,
      path: `M1593,721h-16V705h16Z`,
    },
    {
      id: 2125,
      title: `G-Energy`,
      logoSrc: ``,
      synonyms: ['G-Energy'],
      description: ``,
      discount: new Set(),
      category: new Set(['Другое']),
      audience: new Set(),
      shopURL: `/shop/223`,
      path: `M1633,721h-16V705h16Z`,
    },
    {
      id: 2126,
      title: `#ошарашим32`,
      logoSrc: ``,
      synonyms: [
        'ошарашим',
        '#ошарашим',
        'шары',
        'воздушные шары',
        'воздушные фигуры',
        'фигура из шаров',
      ],
      description: `Украшение детских праздников`,
      discount: new Set(),
      category: new Set([categoryFilter[`Другое`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/190`,
      path: `M2081,645.25v16h-16v-16Z`,
    },
    {
      id: 2127,
      title: `Виртуальный ЗАГС`,
      logoSrc: ``,
      synonyms: ['Виртуальный ЗАГС'],
      description: `Развлекательный киоск`,
      discount: new Set(),
      category: new Set([categoryFilter[`Услуги`]]),
      audience: new Set(),
      shopURL: `/dynamic/uslugi/113`,
      path: ``,
    },
    {
      id: 2128,
      title: `Bambinizon`,
      logoSrc: ``,
      synonyms: [
        'bambinzon',
        'bambi',
        'комбинезон',
        'детская одежда',
        'бамбинезон',
      ],
      description: `Развлекательный киоск`,
      discount: new Set(),
      category: new Set([categoryFilter[`Детские товары и одежда`]]),
      audience: new Set([audienceFilter[`Для детей`]]),
      shopURL: `/shop/24`,
      path: `M1717,743h-16V727h16Z`,
    },
    {
      id: 2130,
      title: `Газированная вода`,
      logoSrc: ``,
      synonyms: [
        'Газированная вода',
        'вендинговый аппарат',
        'газированные напитки',
        'газвода',
      ],
      description: `Автомат по продаже газированной воды и напитков`,
      discount: new Set(),
      category: new Set([categoryFilter[`Кафе и рестораны`]]),
      audience: new Set(),
      shopURL: `/dynamic/eat/87`,
      path: `M2395,608v12h-12V608Z`,
    },
    {
      id: 2131,
      title: `Dress Code`,
      logoSrc: `d-o.svg`,
      synonyms: ['дресс', 'dress', 'drees', 'дрэс', 'код', 'dress code', 'cod'],
      description: `Одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Одежда и аксессуары`]]),
      audience: new Set(),
      shopURL: `/shop/42`,
      path: `M1849.13,784.82h-49.27V751.14h49.27Z`,
    },
    {
      id: 2132,
      title: ``,
      logoSrc: ``,
      synonyms: [],
      description: `Скоро открытие`,
      discount: new Set(),
      category: new Set(),
      audience: new Set(),
      shopURL: ``,
      path: `M2348,507v66h-49V507Z`,
    },
    {
      id: 2133,
      title: `Demix`,
      logoSrc: `demix.svg`,
      synonyms: ['demix', 'демикс', 'дэмикс', 'вуьшч'],
      description: `Спортивная одежда`,
      discount: new Set(),
      category: new Set([categoryFilter[`Спортивные товары и одежда`]]),
      audience: new Set(),
      shopURL: `/shop/220`,
      path: `M1966,669v34h-66.5V587.94h51.18V604.5H2000V669Z`,
    },
    {
      id: 2134,
      title: `Mercedes`,
      logoSrc: ``,
      synonyms: ['Mercedes', 'мерседес'],
      description: `Инсталляция`,
      discount: new Set(),
      category: new Set([categoryFilter[`Другое`]]),
      audience: new Set(),
      shopURL: ``,
      path: `M1084,736h-16V720h16Z`,
    },
    {
      id: 2135,
      title: ``,
      free: true,
      logoSrc: ``,
      synonyms: [],
      description: `Помещение для магазина`,
      discount: new Set(),
      category: new Set(),
      audience: new Set(),
      shopURL: ``,
      path: `M2200.38,784.82V750.5h40.2v41.75h-40.2Z`,
    },
  ],
  helpMarkers: [
    {
      symbolId: `elevator`,
      points: [
        {
          title: `Лифт`,
          position: [1234, 413],
        },
        {
          title: `Лифт`,
          position: [1710, 574],
        },
        {
          title: `Лифт`,
          position: [2296, 419],
        },
      ],
    },
    {
      symbolId: `escalator`,
      points: [
        {
          title: `Эскалатор`,
          position: [1138, 495],
        },
        {
          title: `Эскалатор`,
          position: [1234, 320],
        },
        {
          title: `Эскалатор`,
          position: [1799.44, 719],
        },
        {
          title: `Эскалатор`,
          position: [2340, 719],
        },
        {
          title: `Эскалатор`,
          position: [2340, 476],
        },
        {
          title: `Эскалатор`,
          position: [2014, 465],
        },
        {
          title: `Эскалатор`,
          position: [1167, 556],
        },
      ],
    },
    {
      symbolId: 'entrance-vertical',
      points: [
        {
          title: 'Вход в OBI',
          position: [657, 679],
        },
      ],
    },
    {
      symbolId: 'entrance-diagonal',
      points: [
        {
          title: 'Вход №7',
          position: [1022, 763],
        },
      ],
    },
    {
      symbolId: `wc`,
      points: [
        {
          title: `Туалет`,
          position: [2573, 487.51],
        },
        {
          title: `Туалет`,
          position: [1019.57, 608.94],
        },
      ],
    },
    {
      symbolId: `disabled`,
      points: [
        {
          title: `Туалет для ММГ`,
          position: [1045.81, 608.94],
        },
        {
          title: `Туалет для ММГ`,
          position: [2573, 515],
        },
      ],
    },
    {
      symbolId: `wardrobe`,
      points: [
        {
          title: `Гардероб`,
          position: [1098.28, 608.94],
        },
      ],
    },
    {
      symbolId: `baby-care`,
      points: [
        {
          title: `Комната матери и ребенка`,
          position: [1072.04, 608.94],
        },
      ],
    },
    {
      symbolId: `foodcourt`,
      points: [
        {
          title: `Фуд-корт`,
          position: [2461, 711.02],
        },
      ],
    },
    {
      symbolId: `highchair`,
      points: [
        {
          title: `Детский стульчик`,
          position: [2511.86, 799.02],
        },
      ],
    },
  ],
};
